[package]
name = "image_converter"
version = "1.0.1"
edition = "2025"

[dependencies]
image = "0.24.7"
clap = { version = "4.5.4", features = ["derive"] }
webp = "0.3.0"
dialoguer = "0.11"
ndarray = "0.15"
onnxruntime = "0.0.14"
colored = "2.1"
palette = "0.7.6"
kmeans_colors = "0.7.0"