[package]
name = "image_converter"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24.7"
clap = { version = "4.5.4", features = ["derive"] }
webp = "0.3.0"
dialoguer = "0.11"
ndarray = "0.15"
onnxruntime = "0.0.14"